import type { CreatorSearchResult } from '@shared/types/discovery';

/**
 * Demo creator profiles shown as fallback when the API returns an error
 * or empty results. These give new visitors a sense of the platform's
 * creator ecosystem while real profiles are still being onboarded.
 */
export const DEMO_CREATORS: CreatorSearchResult[] = [
  {
    id: 'demo-art-001',
    displayName: 'Mina Aoki',
    username: 'mina_aoki',
    avatarUrl: null,
    bio: 'Digital illustrator blending traditional Japanese aesthetics with cyberpunk futures. Selling prints and process videos exclusively on Sovren.',
    nip05Verified: true,
    categories: ['Art'],
    tags: ['illustration', 'digital-art', 'cyberpunk'],
    followerCount: 4820,
    contentCount: 137,
    verified: true,
    createdAt: '2025-11-15T10:30:00Z',
  },
  {
    id: 'demo-writing-002',
    displayName: 'Luca Ferreira',
    username: 'luca_writes',
    avatarUrl: null,
    bio: 'Poet and novelist exploring identity through speculative fiction. Weekly serialized chapters and poetry drops funded entirely by Lightning tips.',
    nip05Verified: true,
    categories: ['Writing'],
    tags: ['poetry', 'fiction', 'serial-novel'],
    followerCount: 2340,
    contentCount: 89,
    verified: true,
    createdAt: '2025-12-03T14:00:00Z',
  },
  {
    id: 'demo-music-003',
    displayName: 'Sable Osei',
    username: 'sable_sounds',
    avatarUrl: null,
    bio: 'Indie musician releasing lo-fi beats and ambient soundscapes direct-to-fan. No labels, no middlemen, just music and sats.',
    nip05Verified: false,
    categories: ['Music'],
    tags: ['lo-fi', 'ambient', 'indie'],
    followerCount: 6150,
    contentCount: 52,
    verified: true,
    createdAt: '2025-10-20T08:15:00Z',
  },
  {
    id: 'demo-education-004',
    displayName: 'Dr. Priya Kapoor',
    username: 'priya_btc_edu',
    avatarUrl: null,
    bio: 'Bitcoin educator and former economics professor. Breaking down monetary policy, self-custody, and Lightning development in plain language.',
    nip05Verified: true,
    categories: ['Education'],
    tags: ['bitcoin-education', 'economics', 'tutorials'],
    followerCount: 11200,
    contentCount: 203,
    verified: true,
    createdAt: '2025-09-01T12:00:00Z',
  },
  {
    id: 'demo-photography-005',
    displayName: 'Ren Takahashi',
    username: 'ren_landscapes',
    avatarUrl: null,
    bio: 'Landscape photographer documenting remote wilderness across six continents. High-res prints and behind-the-lens stories available for supporters.',
    nip05Verified: true,
    categories: ['Photography'],
    tags: ['landscape', 'nature', 'travel'],
    followerCount: 8730,
    contentCount: 312,
    verified: true,
    createdAt: '2025-08-12T16:45:00Z',
  },
  {
    id: 'demo-development-006',
    displayName: 'Amara Chen',
    username: 'amara_oss',
    avatarUrl: null,
    bio: 'Open source developer building privacy-first tools. Funding my work through Sovren supporters instead of VC. Ship logs and deep-dives weekly.',
    nip05Verified: true,
    categories: ['Development'],
    tags: ['open-source', 'privacy', 'rust'],
    followerCount: 5490,
    contentCount: 78,
    verified: true,
    createdAt: '2025-11-28T09:30:00Z',
  },
  {
    id: 'demo-podcast-007',
    displayName: 'Marcus Webb',
    username: 'marcus_tech_pod',
    avatarUrl: null,
    bio: 'Tech commentary podcast covering AI, decentralization, and the future of the open web. New episodes every Tuesday, funded by listeners.',
    nip05Verified: false,
    categories: ['Podcast'],
    tags: ['tech', 'AI', 'decentralization'],
    followerCount: 3870,
    contentCount: 145,
    verified: true,
    createdAt: '2025-10-05T11:00:00Z',
  },
  {
    id: 'demo-bitcoin-008',
    displayName: 'Nadia Volkov',
    username: 'nadia_lightning',
    avatarUrl: null,
    bio: 'Lightning Network developer and protocol researcher. Building payment channel tooling and writing technical deep-dives on Layer 2 scaling.',
    nip05Verified: true,
    categories: ['Bitcoin'],
    tags: ['lightning-network', 'protocol', 'layer2'],
    followerCount: 9150,
    contentCount: 64,
    verified: true,
    createdAt: '2025-09-18T13:20:00Z',
  },
];
